id: P010353
initial_creation_type: ocr
source_metadata:
  id: bdr:W21690
  title: ཐང་སྟོང་རྒྱལ་པོའི་རྣམ་ཐར
  author: ''
  volumes:
    4d66940e12504424a74f84e5d0f0b673:
      image_group_id: I4864
      title: ''
      volume_number: 1
      total_pages: 364
